### ISSUE TITLE
Flatten returned model by removing _result and storing data returned from service just under namespace variable.

### ISSUE THREAD

**Issue by tenitram** [Cognifide/knotx#112]
When namespace is used there is no need of having returned data in _result object. Markup would become cleaner when instead of namespace._result.property we would have namespace.property ex:

login._result.errorMessage vs login.errorMessage

**Comment by Skejven** [comment]
Aside of `_result` there is also `_response` object in each namespace (containing e.g. response status code). Because of that we need to keep `_result` also when a namespace is provided..
