### ISSUE TITLE
Repository and Splitter Verticle should become Knots configurable in routing graph on server

### ISSUE THREAD

**Issue by marcinczeczko** [Cognifide/knotx#122]
Currently Repository & Splitter verticles are separate entities not connected with other Knots (previously engines).
After merging 0.6.0 we should:
- Transform Repositories and Splitter into Knot architecture (consuming KnotContext)
- Enable them to be used in the routing graph on server to compose your own processing chain on you will
- this would allow you to configure knot.x e.g. to return html or other assets from repository without any further processing based on path criteria, while other paths will be processed by splitter on other Knots.

**Comment by Skejven** [comment]
There is more accurate concept for Repository and Splitter verticles. They will be part of Knot.x core, which will work on more local-basis to be more performant.
