### ISSUE TITLE
Script attributes name change

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#147]
Proposal attribute names:

data-knot-types -> data-knotx-knots
data-service -> data-knotx-service
data-params -> data-knotx-params
type="text/x-handlebars-template" -> type="text/knotx-snippet"

**Comment by tomaszmichalak** [comment]
Linked with #186.

**Comment by Skejven** [comment]
Looks ok, how about:

- data-knot-types -> knotx-knots
- data-service -> knotx-service
- data-params -> knotx-params

**Comment by tomaszmichalak** [comment]
Changing <script type="text/knotx-snippet"> to <knotx-snippet> could end with some W3C problems? Still if we have unprocessed snippets and Assembler is configured with AS_IS strategy our original snippet definition will go to browser. We should be quite careful with that.

The same comment for all params without data-*.
