### ISSUE TITLE
Knots process only configured Fragments

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#186]
# Overview
This issue is described in https://github.com/Cognifide/knotx/issues/213. This task needs to address all points:
- Change Fragment model to support Knot configuration
- Update example content with correct Knot configurations
- AbstractKnot refactor - remove Handler from API
- Knots filter fragments which should not be processed based on data-knot-types
- Move HTML markup concatenation from HandlebarsKnot to FragmentAssember
- Update documentation

# Current behaviour

Currently Action Knot handles all request with "form.*", Service Knot processes all snippets, Handlebars Knot processes all snippets. We should provide more accurate information about fragments - what Knots should be used for particular snippets. There should not be hidden relationship - if there is "form", Handlebars Knot will be used.

We could change this:
`data-api-type="templating"`
to
`data-knot-types="form123, service, handlebars"`

This will prevent against untapped processing - for example we could have snippert with form which does not require Service Knot (`data-knot-types="form123, handlebars"`).

**Comment by Skejven** [comment]
I like the idea, it may improve request processing performance by e.g. omitting not used knots.

**Comment by tomaszmichalak** [comment]
Agreed, ready to implement.

**Comment by tomaszmichalak** [comment]
Fixed.
