### ISSUE TITLE
Developers guide

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#191]
We need add documentation with:
- how to set up project in IntelliJ and debug code
- how to connect to verticle with remote debugger

**Comment by mmajchrzak** [comment]
Please don't forget about these poor people still working with Eclipse or other IDE

**Comment by tomaszmichalak** [comment]
OK, we can try to provide screens for Eclipse too.

**Comment by tomaszmichalak** [comment]
Done: https://github.com/Cognifide/knotx/wiki/Debugging
