### ISSUE TITLE
Enable reading Knot.x configuration as all files from chosen directory

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#193]
The goal of this task is to enable providing Knot.x configuration with multiple JSON config files.
Currently Knot.x is runned with command:

`java -jar knotx-example-monolith-X.X.X-fat.jar -conf knotx-example-monolith.json`

User should be able to run Knot.x with multiple configuration files, e.g. by:
`java -jar knotx-example-monolith-X.X.X-fat.jar -configDir ./configuration`

Where `configuration` is the directory where JSON config files are stored.

When `configuration` directory contains `knotx-example-monolith.json` file, both commands are equivalent.
When `configuration` directory contains more than one JSON file, all files are merged and treated as a single configuration file.

**Comment by marcinczeczko** [comment]
Better configurations introduced in RC3, closing ticket
