### ISSUE TITLE
Split Knot.x configuration into logical parts

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#194]
Split Knot.x configuration into 4 separate files:
- `core.json` with configuration for server and routing
- `repository.json` with repository configuration,
- `knots.json` with configuration for knots,
- `adapters.json` with configuration for adapters.

This will simplify Knot.x configuration, the goal is user should be able to change frequently only small configuration file `adapters.json` as creating adapters is the most common case when working with Knot.x.

This task depends on #193.

**Comment by marcinczeczko** [comment]
Ability of such configuration is introduced in RC3. Closing ticket
