### ISSUE TITLE
HttpActionAdapter future

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#204]
Knot.x introduced adapters as a light-weight integration layer for different systems / services. Multi-step forms mechanism assumes that we need to get correct `signal` from Adapter. HttpActionAdapter requires from system / services to return `signal` as a part of response - which is bad practice.

Possible changes:
- remove HttpActionAdapter from core source and move it to extensions (this makes multi-step forms impossible to demo)
- move HttpActionAdapter to examples and provide AbstractActionAdapter to simplify project custom development
- leave it as Knot.x Core but provide good javadocs

**Comment by marcinczeczko** [comment]
I'm voting on option 2

**Comment by tomaszmichalak** [comment]
Option 2, agree.

**Comment by marcinczeczko** [comment]
Option 2 implemented
