### ISSUE TITLE
Rewrite Fragment Splitter documentation

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#211]
marcinczeczko 4 days ago Member
This whole paragraph seems to me as something to rewrite - I don't understand what it tires to explain..
what do you mean by context ???
Are you trying to describe what is the fragment from Knot Context point of view or in general ?
Instead simply put explanations that data-knot-types is used for - to say which knots should process the snippet.

**Comment by Skejven** [comment]
Outdated
