### ISSUE TITLE
Knotx Snippet defnition

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#216]
### Current
Fragment Splitter splits Template with a pattern `<script data-knotx-knots=`. So every Knotx snippet must define `data-knotx-knots` attribute and this attribute must be first in attribute in `script` tag. Knotx snippet contains `type="text/knotx-snippet" attribute but now it is not used.

### Proposal
Fragment Splitter splits Template with pattern `<script type="text/knotx-snippet"`. `data-knotx-knots` attribute is optional and if it is not defined all Knots configured in Knots Routing process Fragment. This could be very helpful while prototyping phase where we are not familiar with Knots.

**Comment by Skejven** [comment]
Closing as outdated.
