### ISSUE TITLE
Event Bus local consumers - perfromance improvement

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#262]
**Repository Connector** and **Fragment Assembler** can be registered as event bus local consumers. 

Those two modules do not perform complex operations - first calls Repository for Template, second merges all fragments into one string. Event bus communication requires context serialization what is CPU consuming - see https://github.com/Cognifide/knotx/issues/260. We can advice Vert.x to use in memory models while "local" event bus communication. 

We can add this local consumer option to all modules. This will make Knot.x even more efficient. For the one host deployment strategy the performance will be better.

**Comment by marcinczeczko** [comment]
I'm closing this issue.
The local consumer differs from nonlocal in the visibility within the cluster only. There is no difference how messages are being coded
