### ISSUE TITLE
Hot deployment of templates?

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/knotx#272]
Would it be possible to enable hot deployment of HTML files containing templates? At the moment, Knot.x seems to lock the file, rendering it uneditable, which means it has to be restarted every time the markup is changed.

Here's what happens when I try to save changes to a file while Knot.x is running.

![IntelliJ is unable to save a template while Knot,x is running](https://cloud.githubusercontent.com/assets/8336085/23331007/547d5498-fb5d-11e6-9b79-dc7cff1bb3f5.png)

**Comment by Skejven** [comment]
Hello @toniedzwiedz , thaks for the question.
There should be no problem with replacing/editing the template files.

It looks rather like some bug in IntelliJ (do you use EAP version - I've tested it last weekend and had similar problems with saving html files).

**Comment by toniedzwiedz** [comment]
@Skejven I'm using an older Community version. I'll try upgrading. Thanks.

**Comment by toniedzwiedz** [comment]
@Skejven upgrading to 2016.3.4 did the trick. Closing the issue now. Thanks.
