### ISSUE TITLE
Rewrite headers between request and Template Repository response

### ISSUE THREAD

**Issue by wsatyla** [Cognifide/knotx#29]
Idea is to move response handling from Repositories to Templates
1. Introduce method handle(HttpServerResponse httpServerResponse, Action process, Action done)  in Template interface.
2. Introduce new HttpTemplate which preserve HttpStatus and responseHeaders and implements Template interface.
In handle method apply Actions and rewrite headers - depending on the HttpStatus
3.  Repositories:  in get(...) method create templates and handle it by AsyncResultHandler

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/19471287/17699377/ae7eb142-63c0-11e6-96b9-25944486ee89.jpg)

**Comment by tomaszmichalak** [comment]
Suggested solution:

Template
+ handle(HttpServerResponse response, Action process, Action done)
+ handle(HttpServerResponse response, Action process)

Action
+ handle(Template template)

**Comment by Skejven** [comment]
Please implement this feature using `introduce-javarx` branch as baseline.
Consider following way of changing `HttpRepository` (just a sketch):

```java
private Observable<RepositoryResponse> toRepositoryResponse(Buffer buffer, final HttpClientResponse response) {
        Observable<RepositoryResponse> repositoryResponse;
        if (response.statusCode() == 200) {
            if (buffer.length() > 0) {
                repositoryResponse = RepositoryResponse.success(buffer.toString()).toObservable();
            } else {
                LOGGER.error("Remote repository returned empty template for path `{}`", path);
                repositoryResponse = RepositoryResponse.error("No Template found for path %s", path).toObservable();
            }
        } else if (response.statusCode() == 302) {
            repositoryResponse = RepositoryResponse.error(response.statusCode(), response.headers()).toObservable();
        } else {
            repositoryResponse = RepositoryResponse.error(response.statusCode()).toObservable();
        }
        return repositoryResponse;
    }
```
