### ISSUE TITLE
Customize request routing outside Knots

### ISSUE THREAD

**Issue by mariuszkubis** [Cognifide/knotx#297]
Currently, Knot.X routes every request through `Repository Connector` and `Fragment Splitter` ... `Fragment Assembler`. 
In some scenarios, we want to be able to skip this path and define another. 
A new structure should be introduced (e.g. called `FlowRoute` or `Atom`) which will contain details on how to process the request. `Server` will decide which requests should be routed through which `Atom`. 

In the [current design](https://raw.githubusercontent.com/wiki/Cognifide/knotx/assets/knotx-routing-graph.png), a default `Atom` would wrap the flow from `RepositoryConnector` to `FragmentAssembler`.
In the new solution, we will be able to define new `Atom`s with a custom flow. 

Every `Atom` should define input and output contract.

**Comment by tomaszmichalak** [comment]
This task was implemented in: https://github.com/Cognifide/knotx/pull/299.
