### ISSUE TITLE
Service calls with timeout

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#304]
Knot.x without extensions is able to call REST services and then based on response inject JSON values into placeholders. The problem is no timeout option - so we need to wait until we get a response or an error from a service. We need to be able to define a fallback mechanism for timeouts.

**Comment by Skejven** [comment]
What about [`HttpServiceAdapter` configuration](https://github.com/Cognifide/knotx/wiki/HttpServiceAdapter#how-to-configure)? There is way to configure [`HttpClientOptions`](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientOptions.html) and you can set there [`connetionTimeout`](http://vertx.io/docs/apidocs/io/vertx/core/http/HttpClientOptions.html#setConnectTimeout-int-).

Is that not enough?
Do you mean that there should be separate callback/routing path for service timeouts?
