### ISSUE TITLE
More meaningful error description while starting knotx on bounded port

### ISSUE THREAD

**Issue by nowszy94** [Cognifide/knotx#315]
`io.vertx.core.impl.NoStackTraceThrowable: null`
`io.vertx.core.impl.NoStackTraceThrowable`
`2017-07-26 11:12:09 [vert.x-eventloop-thread-9] ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle`
`.vertx.core.impl.NoStackTraceThrowable: null`
`io.vertx.core.impl.NoStackTraceThrowable`
Above lines are the only error messages, while trying to run knot'x on bounded port. It would be nice, if this case has more meaningful description.

**Comment by tomaszmichalak** [comment]
Fixed in 1.1.2.
