### ISSUE TITLE
Module versioning support

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/knotx#322]
Currently it's not possible to specify module version that should be loaded upon knot.x start.

Let's say we have the following setup:

* knot.x config

```json
{
    "config": {
        "...": "..."
    },
    "modules": [
        "knotx:io.knotx.KnotxServer",
        "knotx:io.knotx.HttpRepositoryConnector",
        "knotx:io.knotx.FragmentSplitter",
        "knotx:io.knotx.FragmentAssembler",
        "knotx:io.knotx.ServiceKnot",
        "knotx:io.knotx.ActionKnot",
        "knotx:io.knotx.HandlebarsKnot",
        "knotx:io.knotx.HttpServiceAdapter",
        "knotx:io.knotx.ResponseProviderKnot",
        "knotx:io.knotx.GatewayKnot",
        "knotx:example.search.images.index"
    ]
}
```
* directory structure

```
.
├── app
│   ├── knotx.jar -> /opt/knotx/author/knotx-standalone-1.1.0.fat.jar
│   ├── search-images-index-0.1.0-SNAPSHOT-knotx.jar -> ../extensions/search-images-index-0.1.0-SNAPSHOT-knotx.jar
│   ├── search-images-index-0.2.0-SNAPSHOT-knotx.jar -> ../extensions/search-images-index-0.2.0-SNAPSHOT-knotx.jar
│   ├── search-images-index-0.2.1-SNAPSHOT-knotx.jar -> ../extensions/search-images-index-0.2.1-SNAPSHOT-knotx.jar
│   └── search-images-index-0.3.0-knotx.jar -> ../extensions/search-images-index-0.3.0-knotx.jar
├── config
│   ├── author.json
│   └── publish.json
├── extensions
│   ├── search-images-index-0.1.0-SNAPSHOT-knotx.jar
│   ├── search-images-index-0.2.0-SNAPSHOT-knotx.jar
│   ├── search-images-index-0.2.1-SNAPSHOT-knotx.jar
│   └── search-images-index-0.3.0-knotx.jar
├── knotx.conf
├── knotx-standalone-1.1.0.fat.jar
└── logback.xml
```

`app/*` is defined as classpath for that knot.x instance.

As listed above we have 4 different versions of the same module and just one reference to `knotx:example.search.images.index` in the config file (w/o version). Because of that it's not possible to determine which version of given module will be used.

I can see a couple of scenarios here:

* the first (hypothetically the oldest) loaded module will be used (with an assumption that modules are loaded/added to classpath in alphabetical order)
* the last (hypothetically the newest) loaded module will be used (same assumption as above)
* module that was loaded first (I'm not sure if filename matters while loading modules from classpath)
* random one will be used (may change with each knot.x restart)
* knot.x fails to start as it's not possible to determine which module version should be loaded

Workaround for now is to use the same filename for each module, so there's no chance for having more than 1 version of given module. That doesn't sound like a long term solution though.

**Comment by marcinczeczko** [comment]
@jwadolowski looks like it would be a nice feature. However, it's not possible to make it happen because it's not a OSGi. The reason behind that is the mentioned `app/` folder is simply a folder from where all classes is to be loaded by regular JVM classloader - it's not a module folder. The same issue would be if you put multiple versions of jar classes into tomcat - you would endup with classloader issue that unknown version of the same jar would be available for your code.
The good practice is to have just one version of jar in `app` folder
