### ISSUE TITLE
Incomplete debug docs

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/knotx#323]
https://github.com/Cognifide/knotx/wiki/Debugging defines how to debug knot.x instance with an assumption that you run it on the same machine as your IDE.

Very often though knot.x is deployed on either completely remote server or local VM that cannot be accessed this way. Additionally official knot.x cookbook allows you to [specify debug port](https://github.com/Knotx/knotx-cookbook/blob/master/attributes/knotx.rb#L45), so there's is a huge chance it is perfectly possible to debug remote instances, but that's just not documented.

**Comment by marcinczeczko** [comment]
Done
