### ISSUE TITLE
knot.x should ignore config parts related to not existing modules 

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/knotx#326]
This is a follow-up of discussion we had on Friday, August 11th.

Currently knot.x won't start if part of its config refer to a module that wasn't added to the classpath. It'd be great if knot.x can detect such situations, print a warning and just carry on. That should help resolve problems with shared config file that multiple modules refer to. 

At the moment if a couple of developers work simultaneously on a totally separate modules they often use shared config file, which forces them to deploy all modules, as knot.x won't be able to start otherwise. That introduces an implicit dependency on a code you either don't care or even don't know that exist, i.e. one team works on stock data integration module, second group develops Solr integration module - there's no connection between them, but shared config file ties them together anyways.

CC: @tomaszmichalak, @Skejven

**Comment by tomaszmichalak** [comment]
Part of 1.1.2 release.
