### ISSUE TITLE
Switch to vertx-codegen 3.5.1 when available

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#346]
In vertx-codegen 3.5.1-SNAPSHOT module is a fix for Jackson dependency:
https://github.com/vert-x3/vertx-codegen/issues/143

We need to switch from 3.5.1-SNAPSHOT to 3.5.1 after release.

**Comment by Skejven** [comment]
Done in `milestone/backpressure-and-configs`.
