### ISSUE TITLE
Full response from repository in case of an error

### ISSUE THREAD

**Issue by karoldrazek** [Cognifide/knotx#355]
Please kindly implement option to return full answer from backend repository to end user in case of status code different than 200.

Currently knotx returns custom error page obfuscating where the issue is.

It would be extremely useful in development process.

**Comment by Skejven** [comment]
@karoldrazek thanks for this ticket. It is good idea and I agree that this behavior should be a default Knot.x behavior (it makes Knot.x transparent).
I agree with `2002, but what  what should happen in case of `404` or `500` returned from the repository? They may contain some body with the template.
Should the Knot.x processing be really disrupted then? Or should it be continued and serve some 404 page with dynamic data included (e.g. signed user name)?

Maybe there should be a repository configuration that enables to list status codes that will trigger Knot.x processing and other codes will be returned as is?

What do you think about that?

**Comment by Skejven** [comment]
This is connected with #48 .
