### ISSUE TITLE
Improve FragmentAssembler UNWRAP and IGNORE strategies 

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#358]
Assembler module uses pattern matching while fragments assembling. It is not good idea for large fragments from performance perspective.

```
public enum UnprocessedFragmentStrategy { 
    ...
    fragment.content().matches(FragmentConstants.ANY_SNIPPET_PATTERN)
    ...
}
```

**Comment by marcinczeczko** [comment]
I'm thinking whether strategies are the good idea at all. I'd rather expect something like this for unprocessed fragments:
- Render HTML comment saying the fragment wasn't processed - maybe with some explanations why
- Do not render anything

And the first option would be available only if fragment processor has config parameter "debug" or "verbose" or something like this...

**Comment by Skejven** [comment]
> Render HTML comment saying the fragment wasn't processed - maybe with some explanations why
I believe this is what more or less [`IGNORE`](https://github.com/Cognifide/knotx/blob/master/knotx-knot/knotx-knot-fragment-assembler/src/main/java/io/knotx/knot/assembler/impl/UnprocessedFragmentStrategy.java#L43) does.

But this is good idea with rendering some debug comment with a reason (might be not easy).

According to performance, maybe we can use: `StringUtils.startsWith(fragment.content(), "<script data-knotx-knots");` ?
Region match should be faster in case of big snippets.
Or maybe this is the time for #107 ?

**Comment by Skejven** [comment]
Also, this is connected with #216 .
