### ISSUE TITLE
Incoming and outgoing request logging

### ISSUE THREAD

**Issue by jwadolowski** [Cognifide/knotx#378]
### Version used

* knot.x: 1.1.2

### Context of the issue/feature

I'd be extremely handy if knot.x can do the following out of the box:
* log all incoming requests in `access.log` file
* make its format configurable (i.e. use apache format by default, but leave an option to add new fields if needed, i.e. custom headers or request processing times)
* write all outgoing requests to a separate file (i.e. all template calls, outgoing requests made by knot.x extensions, etc). When it comes to custom extensions maybe it'd be a good idea to have it by default, so from development point of view it's a built-in feature. To distinguish what extension triggered what request either an identifier in common log can be used or a totally separate file for each extension. Examples:
    * common outgoing request log: 
       ```
        my-1st-extension "GET /remote/endpoint/1"
        my-1st-extension "GET /remote/endpoint/2"
        ...
        my-2nd-extension "POST /yet/another/endpoint"
        ```
    * separate log files, i.e. `my-1st-extension_access.log`, `my-2nd-extension_access.log`, etc

### Bug reproducer

* N/A

### Steps to reproduce

N/A

### Appendix

N/A

**Comment by marcinczeczko** [comment]
@jwadolowski - the full scope of your request will be analyzed for the 1.3 release. At this moment, the comming 1.2 will have a simplified version of the logging (#379), which is just the access log for the HTTP server with a limited logging configuration options - as it inherits it from the vert.x

**Comment by jwadolowski** [comment]
Thanks @marcinczeczko! Even the very basic configuration is a major improvement from my point of view.
