### ISSUE TITLE
Modules monitoring system

### ISSUE THREAD

**Issue by Shaihuludus** [Cognifide/knotx#386]
It would be nice to have health check/monitoring system for checking if all our requested verticles are deployed and working. 

Vertx allows to check how many deploymentIds exist however we can't check what are the names or event bus addresses.

Possible solution: 
Knotx Starter Verticle is already gathering connection between module and deployment id (for logs).
This information could be pass (with event bus address) to MonitoringVerticle which starts as the last one. 

Monitoring verticle would start http server with responses:
 - list of deployed verticles
 - list of failed deployments
 - check if selected verticle is responding on event bus

**Comment by Skejven** [comment]
@Shaihuludus this is already possible with what Knot.x and Vert.x give.
You may use Dropwizard Metric to monitor those endpoints (see more [here](https://github.com/Cognifide/knotx/wiki/KnotxDeployment#vertx-metrics)).

Those metrics works fine e.g. with [Graphite](https://graphiteapp.org/) or [InfluxDB](https://www.influxdata.com/) to gather metrics and you may e.g. display them on [Grafana](https://grafana.com/).
See example board that we use during performance tests:
![monitoring](https://user-images.githubusercontent.com/19705838/35919607-fbcfc7e8-0c15-11e8-9db8-2cb4c5061f57.png)

**Comment by Shaihuludus** [comment]
But we have this warning: "We don’t recommend gathering metrics from your production environment."
That is why I was thinking about tool that could be used on production. Using only logs for checking if production enviroment is working is not the best option. 
Of course we could create such checks in every knot - little overengineering

**Comment by Skejven** [comment]
@Shaihuludus since next minor Knot.x release (1.3) you may want to checkout early version of [Knot.x Dashboard](https://github.com/Knotx/knotx-dashboard). It contains OOTB solution to monitor number of deployed and working verticles and also using e.g. Grafana manage notifications and alerts (e.g. you expect X handlebars verticles but only Y is deployed).
