### ISSUE TITLE
Summarize configuration update in wiki

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#396]
### Context of the issue/feature

Summarize configuration update from #376, #397 and #402 in Upgrade Notes in order to notify the users of the changes that were introduced.

My thoughts:
Dokumentacja

- Getting started
   - How to start knotx with configs
   - From where to get configs 
   - Check that release will send only jars to maven central, configs should be taken manually from github (link to application, bootstrapo configs)
 - Debugging - to change
 - New section: Configuration
    - describe bootstrap.json - how to point application.conf, how to point multiple .conf files, how to point whole folder - how it works (merge all confs), you can still use json - show how, how to control enable/disable scanPeriod, describe how reload works (undeploy & deploy automatically)
    - describe application.conf, how it's structured, major sections, how to use include (consult hocon spec to properly describe includes), required() directive
    - sample config, show how to use cheatsheet.adoc to find option (if not available as comment), and how to set it up in .conf file
    - describe what errors are validated, e.g. if used required() on include fail knotx start if file does not exists, without required() it will ignore - optional include. Describe paramtere reference, e.g. ${global.address.xyz} that fails if wrong reference used

- On each module - do not list all config options - instead point to cheatsheet.adoc on github where all modules have described all available options. only describe how it works
- In modules where we're showing some example configs, e.g. SSL on server, routing, change those examples to HOCON format
- KnotxDeployment - a deployment should be like in starter, such as:
     - lib/ with all jars (knotx fat + any custom modules)
     - conf/ should have bootstrap.json, application.conf, logback.xml
     - java -jar command should set class path as follows -classpath="conf/:lib/*" so configs will be on classpath - then you don't need to provide path to logback config in command line

## My view on chunks of changes:
- [ ] Modify all md docs to use HOCON instead of JSON in any examples
- [ ] Modigy gettingStarted + KnotxDeployment in how to structure application (classpath, where to put configs etc. - starter like)
- [ ] Create new section: Configuration - explaining bootstrap and hocon and struture of the configurations
- [ ] The way how knotx is to be started - see #402

**Comment by marcinczeczko** [comment]
Updated a ticket with the scope of the documentation changes.

**Comment by marcinczeczko** [comment]
Documentation updated
