### ISSUE TITLE
Extract Action Knot to Forms repository

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#436]
### Version used

* knot.x: 1.3.0

### Context of the issue/feature

Knot.x Core should not contain an OpenAPI-based server with a routing mechanism for Knots. But the particular implementations of Knots like Data Bridge, Forms, Templating Engine should be placed in dedicated repositories.

After #430 is implemented, cleanup Action Knot that will be no longer part of the core and move this functionality to [Forms](https://github.com/Knotx/knotx-forms).

Requirements:

* please use Gradle as a build tool
* define contract tests in `it-test` module
* update README.md
* update Knot.x Stack with the new module
* update Knot.x Example Project with the new module
* update Knot.x server configuration
* update tutorials
* cleanup Action Knot
* cleanup wiki: https://github.com/Cognifide/knotx/wiki

### Appendix

* https://github.com/Knotx/knotx-data-bridge
* https://github.com/Knotx/knotx-stack
* https://github.com/Knotx/knotx-example-project

PRs:
https://github.com/Knotx/knotx-forms/pull/1
https://github.com/Cognifide/knotx/pull/444

**Comment by tomaszmichalak** [comment]
This is done here: https://github.com/Knotx/knotx-forms. We expect to adapt Knot.x Forms to Knot.x 2.0 soon.
