### ISSUE TITLE
Assembler with two modes: routing handler, event bus module

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#450]
### Version used

* knot.x: 1.3.0

### Context of the issue/feature

Knot.x server with OpenAPI-based router allows to define custom handlers for particular operations. This is the way how we can configure custom assembler. So we do not have to use the Vert.x Event Bus when we do not plan to scale that module (it prevents serialization overhead for a local assembler).

We should provide the solution where assembler can be configured as a local handler and event bus module (for the cluster mode).

### Appendix

* https://github.com/Cognifide/knotx/blob/feature/request-api-configuration/knotx-core/src/main/java/io/knotx/server/handler/api/RoutingHandlerFactory.java

**Comment by 2kodes** [comment]
Curious if you have the below? scheduled for release in vertx 3.6

[](https://vertx-ci.github.io/web-site-snapshot/docs/vertx-web-api-service/java/)

**Comment by tomaszmichalak** [comment]
Assembler was reimplemented and allows to define it as a custom handler: https://github.com/Knotx/knotx-server-http. Not Vert.x Event Bus option available by default.
