### ISSUE TITLE
Logger issues after running bin/knotx resolve

### ISSUE THREAD

**Issue by 2kodes** [Cognifide/knotx#460]
**Version Used**
knot.x 1.4.0

**Bug description**
After adding vertx dependency to knotx-stack.json and running bin/knotx resolve, running bin/knotx run-knotx will start up knotx but no startup information will be logged to knotx.log. Also there is an error message about multiple SLF4J bindings

**To Reproduce**
1. Add dependency below to knotx-stack.json

 {
      "groupId": "io.vertx",
      "artifactId": "vertx-zookeeper",
      "version": "${vertx.version}",
      "included": true
    }

2. Run bin/knotx resolve
3. After resolution ends run bin/knotx run-knotx
4. Knotx starts up but startup information is not logged to knotx.log.

**Expected behavior**
After resolving dependencies knot.x should run normally and log started verticles to log file

**Screenshots**
![image](https://user-images.githubusercontent.com/2084398/46783992-f69b8b00-cd1b-11e8-8cdc-94a1e075c7ce.png)

**Comment by pawel-przystarz** [comment]
Zookeeper has his own dependency for slf4j, so that's why we get this warns about multiple slf4j bindings. So the simplest way is to add an exclusion to the dependency like that:

` {
      "groupId": "io.vertx",
      "artifactId": "vertx-zookeeper",
      "version": "${vertx.version}",
      "included": true,
      "exclusions": [
        {
          "groupId": "org.slf4j",
          "artifactId": "slf4j-log4j12"
        }
      ]
    } `

**Comment by tomaszmichalak** [comment]
@2kodes I think it should answer your question. Closing the issue.
