### ISSUE TITLE
Improvement: Handling status codes returned by Repository Verticle

### ISSUE THREAD

**Issue by wsatyla** [Cognifide/knotx#48]

**Comment by marcinczeczko** [comment]
Repository Verticle while fetching content from Http Repository can get 200 response with content which is fine and clear how to handle. However there are more scenarios we need to consider:
# Http repository might return
- 404 -> we should back to client as 404
- 500 -> should we back 500 to client ( can be missleading as it would suggest something wrong with Knotx) ? or 404 (might be more clean, template not found on remote repo, becuase it responsed with 500)
- 302 - returned by AEM publisher if CUG are implemented - How should we deal with it ?

**Comment by tomaszmichalak** [comment]
500 -> should we back 500 to client ( can be missleading as it would suggest something wrong with Knotx) ? or 404 (might be more clean, template not found on remote repo, becuase it responsed with 500)

I think that 400 is better in that case. 500 errors should be reserved for Knotx and services (if service configured in that way).

302 - returned by AEM publisher if CUG are implemented. It return 302 redirect to login page - How should we deal with it ?

Knot.x can be connected to different repository sources. In production architecture Apache Front should handle redirects to login pages. Knot.x should not be aware of that.

301 - permament redirect - how should we deal with it ?

Simply return 301 to client.

Other codes ??

I think that Knot.x should return all 3XX, 4XX error code. All 5XX code should be transformed to 400.

**Comment by wiiitek** [comment]
The 400 erro code [means _client error_](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4). This may be misleading as the request itself coulkd be correct. I think we should return the response codes as they have their meaning.

Let's have knot.x simple, doing one thing and doing it good.

**Comment by Skejven** [comment]
I think, that Knot.x should not worry about status codes returned by `http` implementation of repository.
There should be one clear message: "Should markup be processed by template engine or not".
There is special case with redirects but this is not Knot.x responsibility to interpret or act on specific status codes. This is Apache deal.
To sum up, I agree with Tomek:
Knot.x should return all 3XX, 4XX error codes with headers, all 5XX code should be transformed to 400.

Please remember that `http` is not the only (but probably the most used) implementation of repository. E.g. there is `fileSystem` implementation, which decides what to do with 'FileNotFound' or 'IO' exceptions.

**Comment by marcinczeczko** [comment]
I see you point and agree that Knotx shouldn't implement extra logic in this case.
In my opinition it should be like this:
##. Http Repository
### Repo returned 200 with body-> return 200 + body+ headers
### Repo returned 200 with empty body -> return 404 + headers
### Repo returned 2XX (except 200), 3XX, 4XX -> return original code + body(if exists) + headers
### Repo returned 5XX -> return 404 + body (if exists) + headers
## Local Repository
### Repo returned not empty content  -> return 200 + body
### Repo returned empty content -> return 404
### Repo unable to get content (ioexception or others) -> return 404

**Comment by tomaszmichalak** [comment]
> Repo returned 200 with empty body -> return 404 + headers
This is a bit tricky and add additional rule. Do we want to validate content if repository returns 200? 

What do you think about:
**Http Repository
Repo returned 2XX, 3XX, 4XX -> return original code + body(if exists) + headers
Repo returned 5XX -> return 404 + body (if exists) + headers**

**Comment by marcinczeczko** [comment]
Basically this is the same, except that we will return empty content if repo will return it also as empty - the question is if we ok with that ?

**Comment by marcinczeczko** [comment]
As we discussed offline the approach should be very simple. Knot.x shouldn't be reponsible for doing some mappings over status codes returned by repository.
The approach should be as follows:

## Remote repo
 - If statusCode=200 and has body - do the processing
 - If statusCode=200 and no body - return as it is (empty body) keeping the headers and statusCode from repository
 - If statusCode <> 200 - return as it is keeping the headers and statusCode from the repository

## Local repo
 - If local repo successfully retrieved file (has body) - do the processing
 - If local repo successfully retrieved file (empty body) - return as it is (200)
 - If local repo failed due FileNotFoundException - return 404
 - If local repo failed due other error - return 500

**Comment by Skejven** [comment]
Fixed by #359
