### ISSUE TITLE
Update VertX to 3.9.16

### ISSUE THREAD

**Issue by tomasz-sobczyk-wttech** [Cognifide/knotx#520]
**Is your feature request related to a problem? Please describe.**
There are various security issues in KnotX related to outdated version of Vertx. Let's do a bit of maintenance and update KnotX to latest 3.X Vertx version (3.9.16 as of time of writing)

*NOTE:* Pull Requests to all the repos will be provided soon

**Comment by scypio** [comment]
I have prepared the maintenance branches from 1.6.0 tag, but I would need a corresponding branch in 7 knotx repositories. 

These are the forks that are required to rebuild the knotx-stack:

https://github.com/scypio/knotx-dependencies/tree/maintenance/1.7.0
https://github.com/scypio/knotx-junit5/tree/maintenance/1.7.0
https://github.com/scypio/knotx/tree/maintenance/1.7.0
https://github.com/scypio/knotx-template-engine/tree/maintenance/1.7.0
https://github.com/scypio/knotx-data-bridge/tree/maintenance/1.7.0
https://github.com/scypio/knotx-forms/tree/maintenance/1.7.0
https://github.com/scypio/knotx-stack/tree/maintenance/1.7.0

**Comment by malaskowski** [comment]
Hi @scypio, each of repositories have now `knotx-1.x` branch created from `1.6.0` tag.

**Comment by tomaszmichalak** [comment]
We will provide the solution for Knot.x 2.x too.
