### ISSUE TITLE
Knot.x verticles launcher

### ISSUE THREAD

**Issue by marcinczeczko** [Cognifide/knotx#56]

**Comment by Skejven** [comment]
Provide support for [DeploymentOptions](http://vertx.io/docs/apidocs/io/vertx/core/DeploymentOptions.html) in KnotxStandaloneStarterVerticle.
Repository, TemplateEngine and KnotxServer verticles should be started with [configurable number of instances](http://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances).
