### ISSUE TITLE
Test different Knot.x deployment options

### ISSUE THREAD

**Issue by marcinczeczko** [Cognifide/knotx#57]
In this task, prove that scalable Knot.x architecture can be runned in cluster mode on AWS machines. Deploy each Knot.x verticle type (Server [S], Repository [R] and Templating Engine [TE]) on separate machine (architecture consists of 3 servers, each has deployed another type of Knot.x verticle).

**Comment by Skejven** [comment]
This task requires #56 to be implemented.

**Comment by marcinczeczko** [comment]
invalid
