### ISSUE TITLE
Knot.x request/response headers handling

### ISSUE THREAD

**Issue by marcinczeczko** [Cognifide/knotx#69]
After initial discussion we made today, the header handling should be done as follows:
1. Incoming request headers should be passed all the way to the Http Repository
2. Http Repository response headers + status code should be returned to the client
3. Incoming request headers should be passed as it is to the Services
4. Services responses should not have any influence on client response

Diagram below depicts the idea:
![Diagram](https://raw.githubusercontent.com/marcinczeczko/knotx/master/icons/headers-passing.jpg)

Additionally, headers passed to the services can be filtered as follows:
- Service endpoint configuration should have configuration section that allows/denies passing defined headers - supporting wildcards
- preserved headers functionality to be removed.
- Sample configuration (headers configuration should be array to keep the order to allow, deny entries)

``` json
"services": [
        {
          "path": "/service/mock/.*",
          "domain": "localhost",
          "port": 3000,
          "headers" : [
             {"allow" : "*"},
             {"deny" : "X-Forwarder-For"}
          ]
        }, 
        {
          "path": "/service/others/.*",
          "domain": "localhost",
          "port": 5555,
          "headers" : [
             {"deny" : "*"},
             {"allow" : "Host"},
             {"allow" : "X-*"}
          ]
        }, 
```

**Comment by karoldrazek** [comment]
As of configuration:

In my opinion it would be easier to manage if we would define two fields for headers:
1) header.action with values "allow" or "deny"
2) excluded.headers with array of headers that are exclusion from default action

Naming convention is just an example, but it's way easier to keep dynamic sets of single value elements.

What do you think?

Example config:
```json
"services": [
        {
          "path": "/service/mock/.*",
          "domain": "localhost",
          "port": 3000,
          "header.action": "allow",
          "excluded.headers" : [
             "X-Forwarded-For",
             "Set-Cookie"
          ]
        }, 
        {
          "path": "/service/others/.*",
          "domain": "localhost",
          "port": 5555,
          "header.action": "deny",
          "excluded.headers" : [
             "Host",
             "Location",
             "User-Agent"
          ]
        }, 
```
