### ISSUE TITLE
Option to register custom handlebars helpers

### ISSUE THREAD

**Issue by mmajchrzak** [Cognifide/knotx#73]
All available helpers are currently defined in `HandlebarsHelpers` enum. This is not extensible and applications are not able to introduce new helpers with ease. This ticket is to propose a simple mechanism which allows applications to define their own Handlebars helpers.

**Comment by marcinczeczko** [comment]
Good spot. I think we can do simple pluginsteps mechanism using java ServiceLoader

**Comment by mmajchrzak** [comment]
Yeap - I though about something like this. I'll try submitting some solution this week.
