### ISSUE TITLE
Desing Knot.x final modules structure

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#76]
This ticket is to discuss Knot.x project modules structure.
Thought to discuss:
- Create `knotx-eventbus` (thing of better name) module with all eventbus communication models, then divide api (e.g. handlebars and other interfaces that users may want to implement on their own in the future) and models.
- Should there be a separate repository for `knotx-examples` so that only the `core` is in current application repository.

**Comment by Skejven** [comment]
Proposition of new structure for Knot.x project:
**New repository** `knotx-examples` will contain everything that is currently in `knotx-example` module:
- `knotx-mocks` - all mocked pages and examples
- `knotx-example-monolith` - one-jar launcher for examples
- `knotx-adapters-services` - module that will contain examples of `adapter-services`

**Current repository** (https://github.com/Cognifide/knotx) should contain only Knot.x core and documentation. Structure of this repo modules should be:
- `documentation`,
- `icons` -> `assets` or `misc`,
- `knotx-api` - handlebars and other interfaces that users may want to implement on their own in the future,
- `knotx-eventbus` / `knotx-communication` - module with all eventbus communication models,
- `knotx-launcher` - as current,
- `knotx-repository` - as current, but it will contain many `repository` implementations in the future (see #61)
- `knotx-server` - as current,
- `knotx-standalone` - as current,
- `knotx-templating-engine` - as current.

**Comment by mmajchrzak** [comment]
I kind of liked the approach of having the `knotx-example` in the same repository as the code (as per analogy to documentation being versioned along with the code). This way you can make sure that the `knotx-example` is kept up to date with current development and is not abandoned.

**Comment by wiiitek** [comment]
Instead of removing examples module completely, I would rather change them to sth like integration tests. The approach could be changed from
*having a demo easy to setup and show to someone*
to
**having simple and easy tests for separated features of knot.x**

**Comment by wiiitek** [comment]
I'd like to propose two modules instead of current `knotx-example`:

- `knotx-it` - Containing integration tests for various aspects of Knot.X
- `knotx-example` - Saples of how to configure and extend Knot.X that could serve as a demo.

Currently there are two submodules for `knotx-example` but the code could be in one module.

Have you got any remarks on this guys?

**Comment by Skejven** [comment]
I like the idea of separating integration tests and examples.

**Comment by Skejven** [comment]
This will be addressed in Knot.x `1.3` and future releases.
Knot.x will be more modular and core will contain only the real Knot.x core elements like a Server, Repository, Splitter and Assembler.
