### ISSUE TITLE
Extend Knot.x Templating Engine by custom tags processing

### ISSUE THREAD

**Issue by Skejven** [Cognifide/knotx#77]
Custom tags will be placed inside snippet and should be interpreted by Knot.x Templating Engine after Handlebars processing.
Inside custom tags developer will put JSON object that describes tag configuration.
Custom `<knotx>` tags should never be rendered in the final page.

Example of custom tags:

```html
  <script data-api-type="templating" 
      data-uri="/service/mock/second.json"
      type="text/x-handlebars-template">
    <knotx:customTag>
      {
        some options...
      }
    </knotx:customTag>
    <h2>Snippet2 - {{message}}</h2>
    <p>Snippet2 - {{body.a}}</p>
    {{#string_equals status "success"}}<p>Success!</p>{{/string_equals}}
  </script>
```

**Comment by tomaszmichalak** [comment]
One script tag can contain many different knotx custom tags. 
One script tag can contain at most one particular knotx custom tag. 

What do you think about that implementation simplification?

**Comment by marcinczeczko** [comment]
Closing as we will go towards different approach
