### ISSUE TITLE
Nested scripts support

### ISSUE THREAD

**Issue by tomaszmichalak** [Cognifide/knotx#87]
```
<script data-call-get-parent="/parent/123">
  {{if parent.child}}
    <script data-call-get-child="{{parent.child.url}}">
      {{child.data}}
    </script>
  {{endif}}
  {{parent.data}}
</script>
```

/parent/123

```
{
  data: "Parent service result"
  child: {
    url: "/child/123/inner"
  }
}
```

/child/123/inner

```
{
  data: "Child service result"
}
```

Expected result:

```
Child service result
Parent service result
```

**Comment by mmajchrzak** [comment]
+1. Very useful for services using service discovery principle or relied on the order of service invocation.

**Comment by tomaszmichalak** [comment]
This is a concept for future discussion. Has advantages and disadvantages. We mixed adapter service responsibility but simplify development. For now it is open.

**Comment by marcinczeczko** [comment]
Not relevant anymore

**Comment by tomaszmichalak** [comment]
Please update FAQ page before closing.

**Comment by tomaszmichalak** [comment]
Documentation required.
